# DB
url=jdbc:mysql://localhost:3306/fintech?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
username=root
password=Valar@123
driver=com.mysql.cj.jdbc.Driver

# Liquibase
changeLogFile=src/main/resources/Changelog/changelog_DigitalLimit.sql

# HikariCP
db.max.pool.size=10

#Sheduler
org.quartz.scheduler.instanceName = QuartzScheduler
org.quartz.scheduler.instanceId = AUTO
org.quartz.threadPool.class = org.quartz.simpl.SimpleThreadPool
org.quartz.threadPool.threadCount = 5
org.quartz.threadPool.threadPriority = 5
org.quartz.jobStore.class = org.quartz.impl.jdbcjobstore.JobStoreTX
org.quartz.jobStore.driverDelegateClass = org.quartz.impl.jdbcjobstore.StdJDBCDelegate
org.quartz.jobStore.useProperties = false
org.quartz.jobStore.tablePrefix = QRTZ_
org.quartz.jobStore.isClustered = false
org.quartz.jobStore.misfireThreshold = 60000

org.quartz.jobStore.dataSource = myDS

org.quartz.dataSource.myDS.provider = hikaricp
org.quartz.dataSource.myDS.driver = com.mysql.cj.jdbc.Driver
org.quartz.dataSource.myDS.URL = jdbc:mysql://localhost:3306/quartz_db
org.quartz.dataSource.myDS.user = root
org.quartz.dataSource.myDS.password = Valar@123
org.quartz.dataSource.myDS.maxConnections = 5
