# Application DB (Digital Transaction)
app.datasource.url=jdbc:mysql://db:3306/fintech?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
app.datasource.username=root
app.datasource.password=ValarPoo21.
app.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# HikariCP (App DB)
app.datasource.hikari.maximum-pool-size=10

# Liquibase
liquibase.change-log=classpath:Changelog/changelog_DigitalLimit.sql


