# DB
url=jdbc:mysql://localhost:3306/fintech?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
username=root
<<<<<<< HEAD
password=ValarPoo21.
=======
password=Valar@123
>>>>>>> 4dd1b453739300eee62eb23ae25e880f63b07297
driver=com.mysql.cj.jdbc.Driver

# Liquibase
changeLogFile=src/main/resources/Changelog/changelog_DigitalLimit.sql

# HikariCP
db.max.pool.size=10
