# Quartz Scheduler
org.quartz.scheduler.instanceName=QuartzScheduler
org.quartz.scheduler.instanceId=AUTO

org.quartz.threadPool.class=org.quartz.simpl.SimpleThreadPool
org.quartz.threadPool.threadCount=5
org.quartz.threadPool.threadPriority=5

org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX
org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.StdJDBCDelegate
org.quartz.jobStore.useProperties=false
org.quartz.jobStore.tablePrefix=QRTZ_
org.quartz.jobStore.isClustered=false
org.quartz.jobStore.misfireThreshold=60000
org.quartz.core.QuartzScheduler=DEBUG


# Quartz Datasource (LOCALHOST)
org.quartz.jobStore.dataSource=quartzDS
org.quartz.dataSource.quartzDS.provider=hikaricp
org.quartz.dataSource.quartzDS.driver=com.mysql.cj.jdbc.Driver
org.quartz.dataSource.quartzDS.URL=jdbc:mysql://db:3306/mydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
org.quartz.dataSource.quartzDS.user=root
org.quartz.dataSource.quartzDS.password=ValarPoo21.
org.quartz.dataSource.quartzDS.maxConnections=5
