# DB
url=jdbc:mysql://localhost:3306/fintech?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
username=root
password=Valar@123
driver=com.mysql.cj.jdbc.Driver

# Liquibase
changeLogFile=src/main/resources/Changelog/changelog_DigitalLimit.sql

# HikariCP
db.max.pool.size=10
